import type { Service } from '../../../types/services';
import { competePages as fedexDropOffWilloughby } from './fedex-drop-off-willoughby';
import { competePages as fedexDropOffMentor } from './fedex-drop-off-mentor';
import { competePages as fedexDropOffPainesville } from './fedex-drop-off-painesville';
import { competePages as fedexDropOffEastlake } from './fedex-drop-off-eastlake';
import { competePages as fedexDropOffKirtland } from './fedex-drop-off-kirtland';
import { competePages as fedexDropOffChardon } from './fedex-drop-off-chardon';
import { competePages as fedexDropOffMadison } from './fedex-drop-off-madison';
import { competePages as fedexDropOffFairportHarbor } from './fedex-drop-off-fairport-harbor';

/**
 * All competitive landing pages generated by the SB7 Astro page generator.
 * Each generated file exports `competePages: Service[]`.
 * Import and add each new batch here.
 */
export const competitivePages: Service[] = [
  ...fedexDropOffWilloughby,
  ...fedexDropOffMentor,
  ...fedexDropOffPainesville,
  ...fedexDropOffEastlake,
  ...fedexDropOffKirtland,
  ...fedexDropOffChardon,
  ...fedexDropOffMadison,
  ...fedexDropOffFairportHarbor,
];
