import type { Service } from '../../../types/services';
import { competePages as fedexDropOffWilloughby } from './fedex-drop-off-willoughby';
import { competePages as fedexDropOffMentor } from './fedex-drop-off-mentor';
import { competePages as fedexDropOffPainesville } from './fedex-drop-off-painesville';
import { competePages as fedexDropOffEastlake } from './fedex-drop-off-eastlake';
import { competePages as fedexDropOffKirtland } from './fedex-drop-off-kirtland';
import { competePages as fedexDropOffChardon } from './fedex-drop-off-chardon';
import { competePages as fedexDropOffMadison } from './fedex-drop-off-madison';
import { competePages as fedexDropOffFairportHarbor } from './fedex-drop-off-fairport-harbor';
import { competePages as happyReturnsWilloughby } from './happy-returns-willoughby';
import { competePages as happyReturnsMentor } from './happy-returns-mentor';
import { competePages as happyReturnsPainesville } from './happy-returns-painesville';
import { competePages as happyReturnsEastlake } from './happy-returns-eastlake';
import { competePages as happyReturnsKirtland } from './happy-returns-kirtland';
import { competePages as happyReturnsChardon } from './happy-returns-chardon';
import { competePages as happyReturnsMadison } from './happy-returns-madison';
import { competePages as happyReturnsFairportHarbor } from './happy-returns-fairport-harbor';
import { competePages as upsDropOffWilloughby } from './ups-drop-off-willoughby';
import { competePages as upsDropOffMentor } from './ups-drop-off-mentor';
import { competePages as upsDropOffPainesville } from './ups-drop-off-painesville';
import { competePages as upsDropOffEastlake } from './ups-drop-off-eastlake';
import { competePages as upsDropOffKirtland } from './ups-drop-off-kirtland';
import { competePages as upsDropOffChardon } from './ups-drop-off-chardon';
import { competePages as upsDropOffMadison } from './ups-drop-off-madison';
import { competePages as upsDropOffFairportHarbor } from './ups-drop-off-fairport-harbor';
import { competePages as dhlDropOffWilloughby } from './dhl-drop-off-willoughby';
import { competePages as dhlDropOffMentor } from './dhl-drop-off-mentor';
import { competePages as dhlDropOffPainesville } from './dhl-drop-off-painesville';
import { competePages as dhlDropOffEastlake } from './dhl-drop-off-eastlake';
import { competePages as dhlDropOffKirtland } from './dhl-drop-off-kirtland';
import { competePages as dhlDropOffChardon } from './dhl-drop-off-chardon';
import { competePages as dhlDropOffMadison } from './dhl-drop-off-madison';
import { competePages as dhlDropOffFairportHarbor } from './dhl-drop-off-fairport-harbor';
import { competePages as fedexOfficeAltWilloughby } from './fedex-office-alternative-willoughby';
import { competePages as fedexOfficeAltMentor } from './fedex-office-alternative-mentor';
import { competePages as fedexOfficeAltPainesville } from './fedex-office-alternative-painesville';
import { competePages as fedexOfficeAltEastlake } from './fedex-office-alternative-eastlake';
import { competePages as fedexOfficeAltKirtland } from './fedex-office-alternative-kirtland';
import { competePages as fedexOfficeAltChardon } from './fedex-office-alternative-chardon';
import { competePages as fedexOfficeAltMadison } from './fedex-office-alternative-madison';
import { competePages as fedexOfficeAltFairportHarbor } from './fedex-office-alternative-fairport-harbor';

/**
 * All competitive landing pages generated by the SB7 Astro page generator.
 * Each generated file exports `competePages: Service[]`.
 * Import and add each new batch here.
 */
export const competitivePages: Service[] = [
  ...fedexDropOffWilloughby,
  ...fedexDropOffMentor,
  ...fedexDropOffPainesville,
  ...fedexDropOffEastlake,
  ...fedexDropOffKirtland,
  ...fedexDropOffChardon,
  ...fedexDropOffMadison,
  ...fedexDropOffFairportHarbor,
  ...happyReturnsWilloughby,
  ...happyReturnsMentor,
  ...happyReturnsPainesville,
  ...happyReturnsEastlake,
  ...happyReturnsKirtland,
  ...happyReturnsChardon,
  ...happyReturnsMadison,
  ...happyReturnsFairportHarbor,
  ...upsDropOffWilloughby,
  ...upsDropOffMentor,
  ...upsDropOffPainesville,
  ...upsDropOffEastlake,
  ...upsDropOffKirtland,
  ...upsDropOffChardon,
  ...upsDropOffMadison,
  ...upsDropOffFairportHarbor,
  ...dhlDropOffWilloughby,
  ...dhlDropOffMentor,
  ...dhlDropOffPainesville,
  ...dhlDropOffEastlake,
  ...dhlDropOffKirtland,
  ...dhlDropOffChardon,
  ...dhlDropOffMadison,
  ...dhlDropOffFairportHarbor,
  ...fedexOfficeAltWilloughby,
  ...fedexOfficeAltMentor,
  ...fedexOfficeAltPainesville,
  ...fedexOfficeAltEastlake,
  ...fedexOfficeAltKirtland,
  ...fedexOfficeAltChardon,
  ...fedexOfficeAltMadison,
  ...fedexOfficeAltFairportHarbor,
];
